### ISSUE TITLE
sintesis

### ISSUE THREAD

**Issue by ang3-l32** [SistemasTecTlaxiaco/actividad-3-sintesis-ang3-l32#2]
[GP_unidad1_Sintesis_AngelesGonzalezMartinez.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-ang3-l32/files/12516110/GP_unidad1_Sintesis_AngelesGonzalezMartinez.pdf)

**Comment by NoeliaGlez** [comment]
Calificación: 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
